import type { Metadata } from "next";
import { Zen_Kaku_Gothic_New } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/navbar";

export const zenKaku = Zen_Kaku_Gothic_New({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-zen-kaku",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${zenKaku.className}  antialiased flex justify-center`}>
        <div className="flex flex-col w-full items-center">
          <Navbar />
          <main className="flex flex-col p-6 md:p-16 w-full xl:max-w-5xl">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
